/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinMeetingIdRouteImport } from './routes/join/$meetingId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeetingsIndexRouteImport } from './routes/_authenticated/meetings/index'
import { Route as AuthenticatedMeetingTypesIndexRouteImport } from './routes/_authenticated/meeting-types/index'
import { Route as AuthenticatedMeetingsNewRouteImport } from './routes/_authenticated/meetings/new'
import { Route as AuthenticatedMeetingTypesNewRouteImport } from './routes/_authenticated/meeting-types/new'
import { Route as AuthenticatedMeetingTypesMeetingTypeIdEditRouteImport } from './routes/_authenticated/meeting-types/$meetingTypeId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinMeetingIdRoute = JoinMeetingIdRouteImport.update({
  id: '/join/$meetingId',
  path: '/join/$meetingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsIndexRoute =
  AuthenticatedMeetingsIndexRouteImport.update({
    id: '/meetings/',
    path: '/meetings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingTypesIndexRoute =
  AuthenticatedMeetingTypesIndexRouteImport.update({
    id: '/meeting-types/',
    path: '/meeting-types/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsNewRoute =
  AuthenticatedMeetingsNewRouteImport.update({
    id: '/meetings/new',
    path: '/meetings/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingTypesNewRoute =
  AuthenticatedMeetingTypesNewRouteImport.update({
    id: '/meeting-types/new',
    path: '/meeting-types/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingTypesMeetingTypeIdEditRoute =
  AuthenticatedMeetingTypesMeetingTypeIdEditRouteImport.update({
    id: '/meeting-types/$meetingTypeId/edit',
    path: '/meeting-types/$meetingTypeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join/$meetingId': typeof JoinMeetingIdRoute
  '/meeting-types/new': typeof AuthenticatedMeetingTypesNewRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/meeting-types/': typeof AuthenticatedMeetingTypesIndexRoute
  '/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/meeting-types/$meetingTypeId/edit': typeof AuthenticatedMeetingTypesMeetingTypeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/join/$meetingId': typeof JoinMeetingIdRoute
  '/meeting-types/new': typeof AuthenticatedMeetingTypesNewRoute
  '/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/meeting-types': typeof AuthenticatedMeetingTypesIndexRoute
  '/meetings': typeof AuthenticatedMeetingsIndexRoute
  '/meeting-types/$meetingTypeId/edit': typeof AuthenticatedMeetingTypesMeetingTypeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/join/$meetingId': typeof JoinMeetingIdRoute
  '/_authenticated/meeting-types/new': typeof AuthenticatedMeetingTypesNewRoute
  '/_authenticated/meetings/new': typeof AuthenticatedMeetingsNewRoute
  '/_authenticated/meeting-types/': typeof AuthenticatedMeetingTypesIndexRoute
  '/_authenticated/meetings/': typeof AuthenticatedMeetingsIndexRoute
  '/_authenticated/meeting-types/$meetingTypeId/edit': typeof AuthenticatedMeetingTypesMeetingTypeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/dashboard'
    | '/join/$meetingId'
    | '/meeting-types/new'
    | '/meetings/new'
    | '/meeting-types/'
    | '/meetings/'
    | '/meeting-types/$meetingTypeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/dashboard'
    | '/join/$meetingId'
    | '/meeting-types/new'
    | '/meetings/new'
    | '/meeting-types'
    | '/meetings'
    | '/meeting-types/$meetingTypeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/join/$meetingId'
    | '/_authenticated/meeting-types/new'
    | '/_authenticated/meetings/new'
    | '/_authenticated/meeting-types/'
    | '/_authenticated/meetings/'
    | '/_authenticated/meeting-types/$meetingTypeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  JoinMeetingIdRoute: typeof JoinMeetingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$meetingId': {
      id: '/join/$meetingId'
      path: '/join/$meetingId'
      fullPath: '/join/$meetingId'
      preLoaderRoute: typeof JoinMeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/': {
      id: '/_authenticated/meetings/'
      path: '/meetings'
      fullPath: '/meetings/'
      preLoaderRoute: typeof AuthenticatedMeetingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting-types/': {
      id: '/_authenticated/meeting-types/'
      path: '/meeting-types'
      fullPath: '/meeting-types/'
      preLoaderRoute: typeof AuthenticatedMeetingTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/new': {
      id: '/_authenticated/meetings/new'
      path: '/meetings/new'
      fullPath: '/meetings/new'
      preLoaderRoute: typeof AuthenticatedMeetingsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting-types/new': {
      id: '/_authenticated/meeting-types/new'
      path: '/meeting-types/new'
      fullPath: '/meeting-types/new'
      preLoaderRoute: typeof AuthenticatedMeetingTypesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting-types/$meetingTypeId/edit': {
      id: '/_authenticated/meeting-types/$meetingTypeId/edit'
      path: '/meeting-types/$meetingTypeId/edit'
      fullPath: '/meeting-types/$meetingTypeId/edit'
      preLoaderRoute: typeof AuthenticatedMeetingTypesMeetingTypeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeetingTypesNewRoute: typeof AuthenticatedMeetingTypesNewRoute
  AuthenticatedMeetingsNewRoute: typeof AuthenticatedMeetingsNewRoute
  AuthenticatedMeetingTypesIndexRoute: typeof AuthenticatedMeetingTypesIndexRoute
  AuthenticatedMeetingsIndexRoute: typeof AuthenticatedMeetingsIndexRoute
  AuthenticatedMeetingTypesMeetingTypeIdEditRoute: typeof AuthenticatedMeetingTypesMeetingTypeIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeetingTypesNewRoute: AuthenticatedMeetingTypesNewRoute,
  AuthenticatedMeetingsNewRoute: AuthenticatedMeetingsNewRoute,
  AuthenticatedMeetingTypesIndexRoute: AuthenticatedMeetingTypesIndexRoute,
  AuthenticatedMeetingsIndexRoute: AuthenticatedMeetingsIndexRoute,
  AuthenticatedMeetingTypesMeetingTypeIdEditRoute:
    AuthenticatedMeetingTypesMeetingTypeIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  JoinMeetingIdRoute: JoinMeetingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
